digitalbooks/Django/4.Dstagram/accounts/urls.py
from re import template
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import *

#  http://127.0.0.1:8000/accounts/profile/
# 1. profile 만들기
# 2. profile 페이지가 아닌 페이지로 보내기(a. 장고 설정 변경 /b. 웹 서버에서 설정(redirect))

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),     # default : 관리자 페이지 로그아웃 ==> template_name 지정
    path('register/', register, name='register'),
]

digitalbooks/Django/4.Dstagram/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('photo.urls')),
]

# 디버그 모드일때 static기능을 사용
# 1. 미디어 파일 서버를 별도로 두고 사용
# 2. 웹서버(아파치)에서 별도로 서빙 설정을 한다
from django.conf.urls.static import static
from django.conf import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digitalbooks/Django/4.Dstagram/photo/urls.py
from django.urls import path
# from django.views.generic.detail import DetailView      # 제네릭 뷰는 urls.py에서 바로 사용가능함
from .views import *
from .models import Photo

app_name = 'photo'  # namespace

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', PhotoDetailView.as_view(), name='photo_detail'),  # 제네릭 뷰 사용
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

digitalbooks/Django/4.Dstagram/accounts/models.py
from django.db import models

# Create your models here.

digitalbooks/Django/4.Dstagram/photo/models.py
from distutils.command.upload import upload
import imp
from django.db import models
from django.urls import reverse


from django.contrib.auth.models import User

# 외래키(ForeignKey) : User테이블에서 해당 유저를 찾을 수 있는 주키        <- 내 친구가 가지고 있는 우리집 열쇠
# 주키(PrimartKey) : (User테이블) 1 admin x x x x x                     <- 내가 가지고있는 우리집 열쇠

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')  # on_delete : 작성자계정이 삭제되면 어떻게할거임? // related_name : user에서 photo를 참조하는 이름
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png') # upload_to : 사진을 업로드 할 경로
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)   # auto_now_add : db에 데이터가 등록될 때 현재시간을 등록
    updated = models.DateTimeField(auto_now=True)       # auto_now : db에 데이터가 등록되거나 수정될 때 현재시간을 등록

    class Meta:                     # 옵션을 설정하는 클래스
        ordering = ['-updated']    # updated 필드를 기준으로 정렬(- : 내림차순)

    def __str__(self):              # 관리자 페이지에서 인스턴스의 정보를 보일 때 출력될 내용
        return self.author.username + ' ' + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('photo:photo_datail', args=[self.id])

digitalbooks/Django/4.Dstagram/accounts/forms.py
from django.contrib.auth.models import User
from django import forms

# 폼 : 폼 태그 -> HTML의 태그 -> 프론트에서 사용자의 입력을 받는 인터페이스
# 장고의 폼 : HTML의 폼 역할, 데이터베이스에 저장할 내용의 형식, 제약조건

class RegisterForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    # clean_필드명 : 해당 필드에 대한 validation
    def clean_password2(self):
        cd = self.cleaned_data                                      # 안전한 데이터
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwoed not matched!')
        
        return cd['password2']                                      # 관례적으로 해당 필드의 데이터를 리턴

digitalbooks/Django/4.Dstagram/accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm

# CRUD의 create, update => 입력 form이 필요함 ==> forms.py

def register(request):
    if request.method == 'POST':
        # 회원가입 데이터 입력완료
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user':new_user})
    else:
        # 회원가입 내용 입력하는 상황
        user_form = RegisterForm()
    return render(request, 'registration/register.html', {'form':user_form})

digitalbooks/Django/4.Dstagram/photo/views.py
import imp
from django.shortcuts import render
from .models import Photo
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView  
from django.shortcuts import redirect

# 로그인 권한제어 모듈
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required         # 로그인했는지 확인
def photo_list(request):
    # 보여줄 사진 데이터
    photos = Photo.objects.all()
    return render(request, 'photo/list.html', {'photos':photos})    
    # 첫번째 변수는 항상 request, 두번째 변수는 templates아래의 템플릿 파일의 경로, 세번째 변수는 context변수(html과 views.py의 변수를 매핑)

class PhotoUploadView(LoginRequiredMixin, CreateView):      # 로그인했는지 확인
    model = Photo
    fields = ['photo', 'text']  # 작성자(author), 작성시간(created) 자동
    template_name = 'photo/upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id      # 작성자 매칭(외래키 : 필드명_id)

        if form.is_valid():
            # 데이터가 올바르다면 photo인스턴스를 저장
            form.instance.save()
            return redirect('/')
        
        else:
            return self.render_to_response({'form':form})   # 잘못입력했을 때 기존에 작성했던 form을 다시 보여줌

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'

class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'

class PhotoDetailView(LoginRequiredMixin, DetailView):
    model=Photo
    template_name='photo/detail.html'

digitalbooks/Django/4.Dstagram/photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %}- Delete{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="alert alert-info">
                Do you want to delete {{object}}?   <!--object : 하나, object_list : 여러개-->
            </div>
            <form action="" method="post">    
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Confirm">
            </form>
            
        </div>

    </div>

{% endblock %}

digitalbooks/Django/4.Dstagram/photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}
{% block content %}
    
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p><img src="{{post.photo.url}}" style="width:100%;"></p>
            <button type="button" class="btn btn-xs btn-info">
                {{object.author.username}}
            </button>
            <p>{{object.text|linebreaksbr}}</p>
            <a href="{% url 'photo:photo_delete' pk=object.id%}" class="btn btn-outline-danger btn-sm float-right">Delete</a>
            <a href="{% url 'photo:photo_update' pk=object.id%}" class="btn btn-outline-success btn-sm float-right">Update</a>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {% load disqus_tags %}
            {% disqus_show_comments %}
        </div>
        <div class="col-md-2"></div>
    </div>

{% endblock %}

digitalbooks/Django/4.Dstagram/photo/templates/photo/list.html
{% extends 'base.html' %}
{% block title %}- List{% endblock %}
{% block content %}

    {% for post in photos %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <p><img src="{{post.photo.url}}" style="width:100%;"></p>
                <button type="button" class="btn btn-xs btn-info">
                    {{post.author.username}}
                </button>
                <p>{{post.text|linebreaksbr}}</p>   <!-- | : 템플릿 필터, linebreaksbr : 줄바꿈 문자를 <br>태그로 변환 -->
                <p class="text-right">
                    <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
                </p>
            </div>
        </div>

    {% endfor %}

{% endblock %}

digitalbooks/Django/4.Dstagram/photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title %}- Update{% endblock %}
{% block content %}    

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" enctype="multipart/form-data">    
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Update">
            </form>
        </div>
    </div>

{% endblock %}

digitalbooks/Django/4.Dstagram/photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title %}- Upload{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" enctype="multipart/form-data">    
            <!--enctype="multipart/form-data" : 파일업로드하는 폼에 곡 들어있어야 함(없으면 파일 전송이 안됨)
                action="" : 현재 페이지에서 입력과 후처리를 함
                method="post" : 데이터 전송방식(get은 공격에 취약함)-->
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Upload">
            </form>
            
        </div>

    </div>

{% endblock %}

digitalbooks/Django/4.Dstagram/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Dstagram {% block title %}{% endblock %}</title>
</head>
<body>

<div class="container">
    <header class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Dstagram</a>
            <ul class="nav">
                <li class="nav-item"><a href="/" class="active nav-link ">Home</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a href="#" class="nav-link">Welcome, {{user.get_username}}</a></li>
                <li class="nav-item"><a href="{% url 'photo:photo_upload' %}" class="nav-link">Upload</a></li>      <!--photo:photo_upload => namespace(app name) : name-->
                <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
                <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock %}

    <footer class="footer">
        <p>&copy; 2020 Baepeu. Powered By Django 3</p>
    </footer>
</div>


</body>
</html>